import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased !bg-black max-w-7xl m-auto`}
      >
        <main className="m-18 max-lg:m-12 max-md:m-6">{children}</main>
        <footer className="text-center bg-black/50  w-full backdrop-blur-lg py-4 text-2xl fixed bottom-0 left-1/2 -translate-x-1/2">
          By AZCPCF
        </footer>
      </body>
    </html>
  );
}
